### PR TITLE
Release v3.1.0

### PR DESCRIPTION
**Pull request by JuanitoFatas**
# 🐰  Release v3.1.0! 🎉 🏳️‍🌈

<kbd>[Preview CHANGELOG](https://github.com/jollygoodcode/twemoji/blob/2316aa2bf3f4e1988609d2d6bf60c7acbe4e94f6/CHANGELOG.md#310---20161213)</kbd>

@piratefsh Please take a look 🙏 📿

### CODE REVIEW

**Comment by piratefsh** [comment]
@JuanitoFatas LGTM!

**Comment by piratefsh** [comment]
@JuanitoFatas shall we release this?

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas shall we release this?

Sorry for the delay, just released.

**Comment by piratefsh** [comment]
yay, thanks!

**Pull request merged**
